### ISSUE TITLE
interface trunk native vlan support

### ISSUE THREAD

**Issue by GuyFoetz** [ansible-collections/dellemc.os6#34]
##### SUMMARY

os6_vlan does not support native vlans on trunk ports
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

os6_vlan

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGSansible.cfg) = -o ForwardAgent=yes
DEFAULT_HOST_LISTansible.cfg) = ['inventory.yaml']
HOST_KEY_CHECKINGansible.cfg) = False
INTERPRETER_PYTHONansible.cfg) = auto
```

##### OS / ENVIRONMENT

```bash
show version 

Machine Description............... Dell EMC Networking Switch
System Model ID................... N1548
Machine Type...................... Dell EMC Networking N1548
Serial Number..................... CN0V143P2829809S0055A04
Manufacturer...................... 0xbc00
Burned In MAC Address............. CC48.3ADF.9C48
System Object ID.................. 1.3.6.1.4.1.674.10895.3065
SOC Version....................... BCM56150_A0
HW Version........................ 2
CPLD Version...................... 16
Image File........................ N1500v6.6.3.10
Software Capability............... Stack Limit = 4, VLAN Limit = 512

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.6.3.10    6.6.3.3     6.6.3.10       6.6.3.10
```

##### STEPS TO REPRODUCE

You need an interface in trunk mode and an untagged vlan on that interface

```yaml
os6_interface:
    Gi1/0/1:
      portmode: trunk
      admin: up
os6_vlan:
    vlan 1:
      state: present
      tagged_members:
        - port: Gi1/0/1
          state: present
    vlan 2:
      state: present
      untagged_members:
        - port: Gi1/0/1
          state: present
```

##### EXPECTED RESULTS

```bash
interface Gi1/0/1
switchport trunk native vlan 2
switchport trunk allowed vlan 1
exit
```

##### ACTUAL RESULTS

```bash
interface Gi1/0/1
switchport access vlan 2
switchport trunk allowed vlan 1
exit
```
